
title: Jonáš Hampeis
email: jonas@hampeis.cz
description: >
  I am a web developer focusing on everything JavaScript.
baseurl: "" 
url: "" 
github_username:  jonas-hampeis

# Build settings
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
